### ISSUE TITLE
Is it possible to add Docker or Singularity instructions?

### ISSUE THREAD

**Issue by henrykironde** [gvilitechltd/LibSWIFFT#14]
This is not really important but it would be nice if there are instructions to setup a test virtual environments like Docker and Singularity. 

In this case a developer can clone the repo, and with in a few seconds, they just run a Docker command or Singularity command and the software is installed and tests are running.

Please close  the issue if this is not a feature necessary at this moment.

**Comment by henrykironde** [comment]
Nice. Thank you so much for the addition

**Comment by henrykironde** [comment]
@gvilitech I noticed that you are creating a docker file and building the release. `ARG LIBSWIFFT_VERSION=v1.0.0`
I am wondering how scalable it is for me to test the dev since you have a lot of cool additions to the dev. 
It would be nice to be able to change ARG LIBSWIFFT_VERSION=`master` or to `release` or to `v1.0.0`as users test the tool.
I would also recommend that you add the quick start to README. and probably better if `*Quick start on Linux** >> `*Quick start Using Dockers**
`*Quick start on Linux**: Ensure `docker` is installed and runnable, clone this repository and go to its root directory, and run the command `docker build . && docker run --rm -it $(docker build -q .)` to build and test LibSWIFFT.
`

**Comment by henrykironde** [comment]
Also git could be used to clone the directory based on the revisions if wget is not easy to configure that way
```
RUN apt-get update \        
     apt-get install -y git
RUN git clone 
```

**Comment by yarongvili1** [comment]
> It would be nice to be able to change ARG LIBSWIFFT_VERSION=master

This is supported: add `--build-arg LIBSWIFFT_VERSION=main` to the `docker build` command/s.

> I would also recommend that you add the quick start to README.

I may be missing something here. There is a quick start in the latest version of the README. Do you mean something else?

> probably better if *Quick start on Linux** >> Quick start Using Dockers*

I wrote `on Linux` because the command line `docker build . && docker run --rm -it $(docker build -q .)` is specific to a standard shell on Linux (or similar OSs). Do you think it is necessary to add similar instructions for other OSs?

> Also git could be used

I preferred [wget](https://packages.ubuntu.com/focal/wget)+[zip](https://packages.ubuntu.com/focal/zip), which are smaller packages than [git](https://packages.ubuntu.com/focal/git), to minimize the docker image. Also, repositories tend to be larger and grow over time faster than any of their release packages.
