### ISSUE TITLE
I can't get homomorphism of addition.

### ISSUE THREAD

**Issue by JYT-ad** [gvilitechltd/LibSWIFFT#43]
**Describe the bug**
When I use the arithmetic function `SWIFFT_Add`, the result has no additive homomorphism. 
How do I make the input operation to obtain  additive homomorphism.
I tried addition of elements-wise and addition of the whole input, but I was unable to verify the  additive homomorphism.

My code:

```
#include <iostream>
#include "libswifft/swifft.h"

using namespace std;

int main ()
{
    SWIFFT_ALIGN BitSequence input0[SWIFFT_INPUT_BLOCK_SIZE];
    for (int i = 0; i < SWIFFT_INPUT_BLOCK_SIZE; i++)
    {
        input0[i]= rand()%2;
        printf("%d", input0[i]);
    }
    SWIFFT_ALIGN BitSequence output0[SWIFFT_OUTPUT_BLOCK_SIZE];
    SWIFFT_Compute(input0, output0);
        cout << "index 0" << endl;
    for (int j = 0; j < SWIFFT_OUTPUT_BLOCK_SIZE; j += 2)
    {
        printf("%d\n", output0[j]);
    }

cout << "\n";
        SWIFFT_ALIGN BitSequence input1[SWIFFT_INPUT_BLOCK_SIZE];
    for (int i = 0; i < SWIFFT_INPUT_BLOCK_SIZE; i++)
    {
        input1[i]= rand()%2;
        printf("%d", input1[i]);
    }
    SWIFFT_ALIGN BitSequence output1[SWIFFT_OUTPUT_BLOCK_SIZE];
    SWIFFT_Compute(input1, output1);
        cout << "index 0" << endl;
    for (int j = 0; j < SWIFFT_OUTPUT_BLOCK_SIZE; j += 2)
    {
        printf("%d\n", output1[j]);
    }

    cout << "\n";
        cout << "SWIFFT_Add" << endl;
    SWIFFT_Add(output0, output1);
    for (int l = 0; l < SWIFFT_OUTPUT_BLOCK_SIZE; l+=2)
    {
        printf("%d\n", output0[l]);
    }
    cout << "\n";

    
    SWIFFT_ALIGN BitSequence inputxor[SWIFFT_INPUT_BLOCK_SIZE];
for (int i = 0; i < SWIFFT_INPUT_BLOCK_SIZE; i++)
    {
        
       printf("%d", inputxor[i]);
    }

    SWIFFT_ALIGN BitSequence outputxor[SWIFFT_OUTPUT_BLOCK_SIZE];
    SWIFFT_Compute(inputxor, outputxor);
    cout << "xor" << endl;
    for (int j = 0; j < SWIFFT_OUTPUT_BLOCK_SIZE; j+=2)
    {
        printf("%d\n", outputxor[j]);
    }
}
```

Results:

![Result](https://github.com/JYT-ad/image-store/blob/main/2021-07-16%2012-52-00%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Environment (please complete the following information):**
 - Platform: [desktop ]
 - OS and version: [e.g. Ubuntu 20.04 LTS]
 - Tool-chain and version [e.g. GCC 10.3.0]
 - LibSWIFFT version [e.g. v1.2.0]

**Comment by yarongvili1** [comment]
@JYT-ad: This does not indicate a bug, which is why I'll close this bug-issue. It looks like your expectations of the homomorphism property are not right - please carefully review my notes below.

If I'm reading the code your posted right, it does the following:
# Sets up two random input vectors, called `input0` and `input1`, so that each of their bytes is set to either 0 or 1.
# Computes corresponding two output vectors, called `output0` and `output1`, using `SWIFFT_Compute`.
# Defines an input vector, called `inputxor`, that is left uninitialized.
# Computes the corresponding output vector, called `outputxor`.
It also prints out all vectors.

You also included an image that shows result printouts. However, these printouts do not seem to match the code you posted - I see "input sum" in the printouts but not in the code. I'll assume that the vector printouts match.

A few expectations to make sure you have right:
# The input vectors is composed of bits, not bytes. It therefore has a length of `8*SWIFFT_INPUT_BLOCK_SIZE`. If you want a random vector, you should randomize all bits; the modulo-2 operation in the code is unnecessary in this respect.
# Each bit in the input vector is interpreted as a value, either 0 or 1, in the field `Z_{257}`, i.e., modulo-257. A XOR-operation over the input bits is addition modulo-2, not modulo-257. So, even if you initialized `inputxor` to the XOR of `input0` and `input1`, you would still not get your homomorphism-check to pass.
# The homomorphism property is observed when a carry vector is included. If you set up an input vector `inputc` as the bitwise-AND of `input0` and `input1`, and compute its corresponding output vector `outputc`, then adding `output0` and `output1` and twice `outputc` will match `outputxor` (given `inputxor` is correctly initialized). There are [several test-cases](https://github.com/gvilitechltd/LibSWIFFT/blob/v1.2.0/test/swifft_catch.cpp#L812-L976) (of adding 3 input vectors, rather than 2) of the homomorphism property in the library, I recommend studying these test-cases to better understand the homomorphism property.
